apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-ferret
  labels:
    name: parsec-ferret
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:parsec_ferret
        name: parsec-ferret
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "./run -a run -S parsec -p ferret -i native -n 2"]
      restartPolicy: Never
      nodeSelector:
        # cca-project-nodetype: "parsec"
        kubernetes.io/hostname: node-a-2core-fltk
      affinity:
        # (hard) never with Memcached, Canneal, Dedup
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - some-memcached
                - parsec-canneal
                - parsec-dedup
            topologyKey: kubernetes.io/hostname