apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-radix
  labels:
    name: parsec-radix
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:splash2x_radix
        name: parsec-radix
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "./run -a run -S splash2x -p radix -i native -n 4"]
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: node-d-4core-cr77